/* =========       RESET DB's + S3        ========== */

USE ROLE ACCOUNTADMIN;
DROP DATABASE IF EXISTS GUIDEWIRE_CDA;
DROP WAREHOUSE IF EXISTS GW_CDA_LOAD_WH;


/* =========       SET UP RBAC, WH + DB's     ======== */

-- Create the guidewire admin role 
CREATE ROLE IF NOT EXISTS GUIDEWIRE_ADMIN;
GRANT ROLE GUIDEWIRE_ADMIN TO ROLE SYSADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE GUIDEWIRE_ADMIN;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE GUIDEWIRE_ADMIN;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE GUIDEWIRE_ADMIN;
USE ROLE GUIDEWIRE_ADMIN;
CREATE OR REPLACE WAREHOUSE GW_CDA_LOAD_WH;
CREATE OR REPLACE DATABASE GUIDEWIRE_CDA;
CREATE OR REPLACE SCHEMA GUIDEWIRE_CDA.LANDING;
CREATE OR REPLACE SCHEMA GUIDEWIRE_CDA.RAW;
CREATE OR REPLACE SCHEMA GUIDEWIRE_CDA.ENTERPRISE;

CREATE OR REPLACE FILE FORMAT GUIDEWIRE_CDA.PUBLIC.FILE_FORMAT_PARQUET_DEFAULT 
    TYPE = 'PARQUET' COMPRESSION = 'AUTO' BINARY_AS_TEXT = TRUE;


/* =========       SET UP s3 ACCESS        ========== */

show storage integrations;

-- 1. STORAGE INTEGRATION: Defines a bucket and Credentials to use

-- REPLACE THIS INTEGRATION NAME WITH ONE YOU HAVE CREATED
DESC INTEGRATION USWEST2_S3_INTEGRATION;

-- 2. EXTERNAL STAGE: Defines a location we can access in s3
CREATE OR REPLACE STAGE GUIDEWIRE_CDA.LANDING.s3_extstg_guidewire
    storage_integration = uswest2_s3_integration -- REPLACE THIS INTEGRATION NAME WITH ONE YOU HAVE CREATED
    url = 's3://sfc-mwies-extstg-uswest2/guidewire_cda/' -- REPLACE THE BUCKET NAME WITH ONE FROM YOUR STORAGE INTEGRATION
    file_format = (type = parquet);
    
rm @GUIDEWIRE_CDA.LANDING.s3_extstg_guidewire/bc_chargept_nm_l10n/4fdc0fa344f7452a8a82f05b5c7cab27/1612480304263/;
rm @GUIDEWIRE_CDA.LANDING.s3_extstg_guidewire/bc_chargept_nm_l10n/4fdc0fa344f7452a8a82f05b5c7cab28/;

-- Query data as-is in s3
list @GUIDEWIRE_CDA.LANDING.s3_extstg_guidewire;  

SELECT 'Reset Complete.' as Status;